apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:  # how every pod should behave
      containers:
        - name: payments # for logging purposes
          image: crs1233/payments
          # image: us.gcr.io/payments-dev-343112/payments # for google cloud
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: STRIPE_KEY
            - name: MONGO_URI
              value: 'mongodb://payments-mongo-srv:27017/payments'
            - name: NATS_CLUSTER_ID
              value: 'ticketing'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name # will return pods name 
            - name: NATS_URL
              value: 'http://nats-srv:4222'
---
apiVersion: v1
kind: Service
metadata:
  name: payments-srv
spec: 
  #type: ClusterIP this is a default service type
  selector:
    app: payments
  ports:
    - name: payments
      protocol: TCP
      port: 3000
      targetPort: 3000
